// export const USER_LOGGED_IN = 'USER_LOGGED_IN';
// export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const PROJECTS_FETCH = 'PROJECTS_FETCH';
export const PROJECTS_ADD = 'PROJECTS_ADD';

//--------- Product --------------
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const POST_PRODUCT_REQUEST = 'POST_PRODUCT_REQUEST';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const POST_PRODUCT_FAILURE = 'POST_PRODUCT_FAILURE';

export const PUT_PRODUCT_REQUEST = 'PUT_PRODUCT_REQUEST';
export const PUT_PRODUCT_SUCCESS = 'PUT_PRODUCT_SUCCESS';
export const PUT_PRODUCT_FAILURE = 'PUT_PRODUCT_FAILURE';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';

export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST'
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'
export const GET_PRODUCT_BY_ID_FAILURE = 'GET_PRODUCT_BY_ID_FAILURE'
//----------------------------------
//---------- Filter ----------------
export const GET_MATERIAL_FILTER_REQUEST = 'GET_MATERIAL_FILTER_REQUEST';
export const GET_MATERIAL_FILTER_SUCCESS = 'GET_MATERIAL_FILTER_SUCCESS';
export const GET_MATERIAL_FILTER_FAILURE = 'GET_MATERIAL_FILTER_FAILURE';

export const GET_FRACTION_FILTER_REQUEST = 'GET_FRACTION_FILTER_REQUEST';
export const GET_FRACTION_FILTER_SUCCESS = 'GET_FRACTION_FILTER_SUCCESS';
export const GET_FRACTION_FILTER_FAILURE = 'GET_FRACTION_FILTER_FAILURE';

export const GET_AGENCY_FILTER_REQUEST = 'GET_AGENCY_FILTER_REQUEST';
export const GET_AGENCY_FILTER_SUCCESS = 'GET_AGENCY_FILTER_SUCCESS';
export const GET_AGENCY_FILTER_FAILURE = 'GET_AGENCY_FILTER_FAILURE';

export const GET_CATALOG_FILTER_REQUEST = 'GET_CATALOG_FILTER_REQUEST';
export const GET_CATALOG_FILTER_SUCCESS = 'GET_CATALOG_FILTER_SUCCESS';
export const GET_CATALOG_FILTER_FAILURE = 'GET_CATALOG_FILTER_FAILURE';

export const GET_MATERIAL_FORCUS_REQUEST = 'GET_MATERIAL_FORCUS_REQUEST';
export const GET_MATERIAL_FORCUS_SUCCESS = 'GET_MATERIAL_FORCUS_SUCCESS';
export const GET_MATERIAL_FORCUS_FAILURE = 'GET_MATERIAL_FORCUS_FAILURE';

export const GET_FRACTION_FORCUS_REQUEST = 'GET_FRACTION_FORCUS_REQUEST';
export const GET_FRACTION_FORCUS_SUCCESS = 'GET_FRACTION_FORCUS_SUCCESS';
export const GET_FRACTION_FORCUS_FAILURE = 'GET_FRACTION_FORCUS_FAILURE';

export const GET_AGENCY_FORCUS_REQUEST = 'GET_AGENCY_FORCUS_REQUEST';
export const GET_AGENCY_FORCUS_SUCCESS = 'GET_AGENCY_FORCUS_SUCCESS';
export const GET_AGENCY_FORCUS_FAILURE = 'GET_AGENCY_FORCUS_FAILURE';

export const GET_CATALOG_FORCUS_REQUEST = 'GET_CATALOG_FORCUS_REQUEST';
export const GET_CATALOG_FORCUS_SUCCESS = 'GET_CATALOG_FORCUS_SUCCESS';
export const GET_CATALOG_FORCUS_FAILURE = 'GET_CATALOG_FORCUS_FAILURE';
//---------------------- Form Add Fast----------------

export const GET_DISTRIBUTOR_REQUEST = 'GET_DISTRIBUTOR_REQUEST';
export const GET_DISTRIBUTOR_SUCCESS = 'GET_DISTRIBUTOR_SUCCESS';
export const GET_DISTRIBUTOR_FAILURE = 'GET_DISTRIBUTOR_FAILURE';

export const GET_FORM_MATERIAL_REQUEST = 'GET_FORM_MATERIAL_REQUEST';
export const GET_FORM_MATERIAL_SUCCESS = 'GET_FORM_MATERIAL_SUCCESS';
export const GET_FORM_MATERIAL_FAILURE = 'GET_FORM_MATERIAL_FAILURE';

export const GET_FORM_MATERIAL_SEARCH_REQUEST = 'GET_FORM_MATERIAL_SEARCH_REQUEST';
export const GET_FORM_MATERIAL_SEARCH_SUCCESS = 'GET_FORM_MATERIAL_SEARCH_SUCCESS';
export const GET_FORM_MATERIAL_SEARCH_FAILURE = 'GET_FORM_MATERIAL_SEARCH_FAILURE';

export const GET_FORM_FRACTION_REQUEST = 'GET_FORM_FRACTION_REQUEST';
export const GET_FORM_FRACTION_SUCCESS = 'GET_FORM_FRACTION_SUCCESS';
export const GET_FORM_FRACTION_FAILURE = 'GET_FORM_FRACTION_FAILURE';

export const GET_FORM_DISTRIBUTOR_REQUEST = 'GET_FORM_DISTRIBUTOR_REQUEST';
export const GET_FORM_DISTRIBUTOR_SUCCESS = 'GET_FORM_DISTRIBUTOR_SUCCESS';
export const GET_FORM_DISTRIBUTOR_FAILURE = 'GET_FORM_DISTRIBUTOR_FAILURE';

export const GET_FORM_DISTRIBUTOR_ALL_REQUEST = 'GET_FORM_DISTRIBUTOR_ALL_REQUEST';
export const GET_FORM_DISTRIBUTOR_ALL_SUCCESS = 'GET_FORM_DISTRIBUTOR_ALL_SUCCESS';
export const GET_FORM_DISTRIBUTOR_ALL_FAILURE = 'GET_FORM_DISTRIBUTOR_ALL_FAILURE';

export const GET_FORM_CATALOG_ALL_REQUEST = 'GET_FORM_CATALOG_ALL_REQUEST';
export const GET_FORM_CATALOG_ALL_SUCCESS = 'GET_FORM_CATALOG_ALL_SUCCESS';
export const GET_FORM_CATALOG_ALL_FAILURE = 'GET_FORM_CATALOG_ALL_FAILURE';

export const GET_FORM_CATALOG_SEARCH_REQUEST = 'GET_FORM_CATALOG_SEARCH_REQUEST';
export const GET_FORM_CATALOG_SEARCH_SUCCESS = 'GET_FORM_CATALOG_SEARCH_SUCCESS';
export const GET_FORM_CATALOG_SEARCH_FAILURE = 'GET_FORM_CATALOG_SEARCH_FAILURE';

export const GET_FORM_CATALOG_REQUEST = 'GET_FORM_CATALOG_REQUEST';
export const GET_FORM_CATALOG_SUCCESS = 'GET_FORM_CATALOG_SUCCESS';
export const GET_FORM_CATALOG_FAILURE = 'GET_FORM_CATALOG_FAILURE';

export const GET_FORM_AGENCY_REQUEST = 'GET_FORM_AGENCY_REQUEST';
export const GET_FORM_AGENCY_SUCCESS = 'GET_FORM_AGENCY_SUCCESS';
export const GET_FORM_AGENCY_FAILURE = 'GET_FORM_AGENCY_FAILURE';

export const POST_FORM_REQUEST = 'POST_FORM_REQUEST';
export const POST_FORM_SUCCESS = 'POST_FORM_SUCCESS';
export const POST_FORM_FAILURE = 'POST_FORM_FAILURE';

export const POST_FORM_INPUT_REQUEST = 'POST_FORM_INPUT_REQUEST';
export const POST_FORM_INPUT_SUCCESS = 'POST_FORM_INPUT_SUCCESS';
export const POST_FORM_INPUT_FAILURE = 'POST_FORM_INPUT_FAILURE';

export const PUT_FORM_REQUEST = 'PUT_FORM_REQUEST';
//----------------------------------
//--------- Selection --------------
export const GET_SELECTION_REQUEST = 'GET_SELECTION_REQUEST';
export const GET_SELECTION_SUCCESS = 'GET_SELECTION_SUCCESS';
export const GET_SELECTION_FAILURE = 'GET_SELECTION_FAILURE';

export const DELETE_ITEM_SELECTED = 'DELETE_ITEM_SELECTED'
export const CHOOSE_PRODUCT = 'CHOOSE_PRODUCT';
export const CLEAR_NAME = 'CLEAR_NAME';

//---------------------------------
//supplier
export const GET_SUPPLIER_REQUEST = 'GET_SUPPLIER_REQUEST';
export const GET_SUPPLIER_SUCCESS = 'GET_SUPPLIER_SUCCESS';
export const GET_SUPPLIER_FAILURE = 'GET_SUPPLIER_FAILURE';

export const GET_SUPPLIER_NAME_REQUEST = 'GET_SUPPLIER_NAME_REQUEST';
export const GET_SUPPLIER_NAME_SUCCESS = 'GET_SUPPLIER_NAME_SUCCESS';
export const GET_SUPPLIER_NAME_FAILURE = 'GET_SUPPLIER_NAME_FAILURE';

export const ADD_SUPPLIER_NAME_REQUEST = 'ADD_SUPPLIER_NAME_REQUEST';
export const ADD_SUPPLIER_NAME_SUCCESS = 'ADD_SUPPLIER_NAME_SUCCESS';
export const ADD_SUPPLIER_NAME_FAILURE = 'ADD_SUPPLIER_NAME_FAILURE';

export const ADD_SUPPLIER_REQUEST = 'ADD_SUPPLIER_REQUEST';
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_FAILURE = 'ADD_SUPPLIER_FAILURE';

export const UPDATE_SUPPLIER_NAME_ALL_REQUEST = 'UPDATE_SUPPLIER_NAME_ALL_REQUEST';
export const UPDATE_SUPPLIER_NAME_ALL_SUCCESS = 'UPDATE_SUPPLIER_NAME_ALL_SUCCESS';
export const UPDATE_SUPPLIER_NAME_ALL_FAILURE = 'UPDATE_SUPPLIER_NAME_ALL_FAILURE';

export const DELETE_SUPPLIER_NAME_ALL_REQUEST = 'DELETE_SUPPLIER_NAME_ALL_REQUEST';
export const DELETE_SUPPLIER_NAME_ALL_SUCCESS = 'DELETE_SUPPLIER_NAME_ALL_SUCCESS';
export const DELETE_SUPPLIER_NAME_ALL_FAILURE = 'DELETE_SUPPLIER_NAME_ALL_FAILURE';

export const UPDATE_SUPPLIER_REQUEST = 'UPDATE_SUPPLIER_REQUEST';
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS';
export const UPDATE_SUPPLIER_FAILURE = 'UPDATE_SUPPLIER_FAILURE';

export const DELETE_SUPPLIER_REQUEST = 'DELETE_SUPPLIER_REQUEST';
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS';
export const DELETE_SUPPLIER_FAILURE = 'DELETE_SUPPLIER_FAILURE';

export const SEARCH_SUPPLIER_REQUEST = 'SEARCH_SUPPLIER_REQUEST';
export const SEARCH_SUPPLIER_SUCCESS = 'SEARCH_SUPPLIER_SUCCESS';
export const SEARCH_SUPPLIER_FAILURE = 'SEARCH_SUPPLIER_FAILURE';

export const SEARCH_SUPPLIER_NAME_REQUEST = 'SEARCH_SUPPLIER_NAME_REQUEST';
export const SEARCH_SUPPLIER_NAME_SUCCESS = 'SEARCH_SUPPLIER_NAME_SUCCESS';
export const SEARCH_SUPPLIER_NAME_FAILURE = 'SEARCH_SUPPLIER_NAME_FAILURE';

export const GET_DETAIL_SUPPLIER_REQUEST = 'GET_DETAIL_SUPPLIER_REQUEST';
export const GET_DETAIL_SUPPLIER_SUCCESS = 'GET_DETAIL_SUPPLIER_SUCCESS';
export const GET_DETAIL_SUPPLIER_FAILURE = 'GET_DETAIL_SUPPLIER_FAILURE';

export const CHOOSE_SUPPLIER_NAME = 'CHOOSE_SUPPLIER_NAME';

export const GET_DISTRIBUTOR_BY_SUP_NAME_REQUEST = 'GET_DISTRIBUTOR_BY_SUP_NAME_REQUEST';
export const GET_DISTRIBUTOR_BY_SUP_NAME_SUCCESS = 'GET_DISTRIBUTOR_BY_SUP_NAME_SUCCESS';
export const GET_DISTRIBUTOR_BY_SUP_NAME_FAILURE = 'GET_DISTRIBUTOR_BY_SUP_NAME_FAILURE';

export const ADD_DISTRIBUTOR_BY_SUP_NAME_REQUEST = 'ADD_DISTRIBUTOR_BY_SUP_NAME_REQUEST';
export const ADD_DISTRIBUTOR_BY_SUP_NAME_SUCCESS = 'ADD_DISTRIBUTOR_BY_SUP_NAME_SUCCESS';
export const ADD_DISTRIBUTOR_BY_SUP_NAME_FAILURE = 'ADD_DISTRIBUTOR_BY_SUP_NAME_FAILURE';

export const UPDATE_DISTRIBUTOR_BY_SUP_NAME_REQUEST = 'UPDATE_DISTRIBUTOR_BY_SUP_NAME_REQUEST';
export const UPDATE_DISTRIBUTOR_BY_SUP_NAME_SUCCESS = 'UPDATE_DISTRIBUTOR_BY_SUP_NAME_SUCCESS';
export const UPDATE_DISTRIBUTOR_BY_SUP_NAME_FAILURE = 'UPDATE_DISTRIBUTOR_BY_SUP_NAME_FAILURE';

export const DELETE_DISTRIBUTOR_BY_SUP_NAME_REQUEST = 'DELETE_DISTRIBUTOR_BY_SUP_NAME_REQUEST';
export const DELETE_DISTRIBUTOR_BY_SUP_NAME_SUCCESS = 'DELETE_DISTRIBUTOR_BY_SUP_NAME_SUCCESS';
export const DELETE_DISTRIBUTOR_BY_SUP_NAME_FAILURE = 'DELETE_DISTRIBUTOR_BY_SUP_NAME_FAILURE';

export const CHOOSE_SUPPLIER = "CHOOSE_SUPPLIER";

export const UNMOUNT_SUPPLIER = 'UNMOUNT_SUPPLIER';
//Add infomations for project
export const ADD_AREA = 'ADD_AREA';
export const DELETE_AREA = 'DELETE_AREA';
export const ADD_CODE_CONTRACT = 'ADD_CODE_CONTRACT';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';

//Drop project
export const DROP_PROJECT_REQUEST = 'DROP_PROJECT_REQUEST'
export const DROP_PROJECT_SUCCESS = 'DROP_PROJECT_SUCCESS'
export const DROP_PROJECT_FAILURE = 'DROP_PROJECT_FAILURE'

//copy project
export const COPY_PROJECT_REQUEST = 'COPY_PROJECT_REQUEST'
export const COPY_PROJECT_SUCCESS = 'COPY_PROJECT_SUCCESS'
export const COPY_PROJECT_FAILURE = 'COPY_PROJECT_FAILURE'

//Save project
export const SAVE_PROJECT_REQUEST = 'SAVE_PROJECT_REQUEST'
export const SAVE_PROJECT_SUCCESS = 'SAVE_PROJECT_SUCCESS'
export const SAVE_PROJECT_FAILURE = 'SAVE_PROJECT_FAILURE'

export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE'
// copy product to areas
export const COPY_PRODUCT_TO_AREA = 'COPY_PRODUCT_TO_AREA'
export const CANCEL_COPY_PRODUCT_TO_AREA = 'CANCEL_COPY_PRODUCT_TO_AREA'

export const SAVE_SIZE = 'SAVE_SIZE'
export const SAVE_NOTE = 'SAVE_NOTE'
export const SAVE_DESCRIPTION = 'SAVE_DESCRIPTION'

//Drop item
export const DROP_PRODUCT = 'DROP_PRODUCT'

//Choosed product
export const CHOOSED_PRODUCT = 'CHOOSED_PRODUCT'

//Active page
export const ACTIVE_PAGE = 'ACTIVE_PAGE'

//Open list
export const OPEN_LIST = 'OPEN_LIST_AREA'

//Close list
export const CLOSE_LIST = 'CLOSE_LIST_AREA'

//Close product board
export const CLOSE_PRODUCT_BOARD = 'CLOSE_PRODUCT_BOARD'

//Open product board
export const OPEN_PRODUCT_BOARD = 'OPEN_PRODUCT_BOARD'

//Text Note
export const TEXT_NOTE = 'TEXT_NOTE'

export const GET_ALL_SUPPLIER_REQUEST = 'GET_ALL_SUPPLIER_REQUEST'
export const GET_ALL_SUPPLIER_SUCCESS = 'GET_ALL_SUPPLIER_SUCCESS'
export const GET_ALL_SUPPLIER_FAILURE = 'GET_ALL_SUPPLIER_FAILURE'

//MATERIAL
export const GET_MATERIAL_REQUEST = 'GET_MATERIAL_REQUEST';
export const GET_MATERIAL_SUCCESS = 'GET_MATERIAL_SUCCESS';
export const GET_MATERIAL_FAILURE = 'GET_MATERIAL_FAILURE';

export const ADD_MATERIAL_REQUEST = 'ADD_MATERIAL_REQUEST';
export const ADD_MATERIAL_SUCCESS = 'ADD_MATERIAL_SUCCESS';
export const ADD_MATERIAL_FAILURE = 'ADD_MATERIAL_FAILURE';

export const UPDATE_MATERIAL_REQUEST = 'UPDATE_MATERIAL_REQUEST';
export const UPDATE_MATERIAL_SUCCESS = 'UPDATE_MATERIAL_SUCCESS';
export const UPDATE_MATERIAL_FAILURE = 'UPDATE_MATERIAL_FAILURE';

export const DELETE_MATERIAL_REQUEST = 'DELETE_MATERIAL_REQUEST';
export const DELETE_MATERIAL_SUCCESS = 'DELETE_MATERIAL_SUCCESS';
export const DELETE_MATERIAL_FAILURE = 'DELETE_MATERIAL_FAILURE';

export const SEARCH_MATERIAL_REQUEST = 'SEARCH_MATERIAL_REQUEST';
export const SEARCH_MATERIAL_SUCCESS = 'SEARCH_MATERIAL_SUCCESS';
export const SEARCH_MATERIAL_FAILURE = 'SEARCH_MATERIAL_FAILURE';

export const CHOOSE_MATERIAL = "CHOOSE_MATERIAL";

//Category
export const GET_CATALOG_REQUEST = 'GET_CATALOG_REQUEST'
export const GET_CATALOG_SUCCESS = 'GET_CATALOG_SUCCESS'
export const GET_CATALOG_FAILURE = 'GET_CATALOG_FAILURE'

export const GET_CATALOG_BY_AGENCY_ID_REQUEST = 'GET_CATALOG_BY_AGENCY_ID_REQUEST'
export const GET_CATALOG_BY_AGENCY_ID_SUCCESS = 'GET_CATALOG_BY_AGENCY_ID_SUCCESS'
export const GET_CATALOG_BY_AGENCY_ID_FAILURE = 'GET_CATALOG_BY_AGENCY_ID_FAILURE'

export const EDIT_CATALOG_REQUEST = 'EDIT_CATALOG_REQUEST'
export const EDIT_CATALOG_SUCCESS = 'EDIT_CATALOG_SUCCESS'
export const EDIT_CATALOG_FAILURE = 'EDIT_CATALOG_FAILURE'

export const ADD_CATALOG_REQUEST = 'ADD_CATALOG_REQUEST'
export const ADD_CATALOG_SUCCESS = 'ADD_CATALOG_SUCCESS'
export const ADD_CATALOG_FAILURE = 'ADD_CATALOG_FAILURE'

export const DELETE_CATALOG_REQUEST = 'DELETE_CATALOG_REQUEST'
export const DELETE_CATALOG_SUCCESS = 'DELETE_CATALOG_SUCCESS'
export const DELETE_CATALOG_FAILURE = 'DELETE_CATALOG_FAILURE'

export const SEARCH_CATALOG_REQUEST = 'SEARCH_CATALOG_REQUEST'
export const SEARCH_CATALOG_SUCCESS = 'SEARCH_CATALOG_SUCCESS'
export const SEARCH_CATALOG_FAILURE = 'SEARCH_CATALOG_FAILURE'

export const SEARCH_CATALOG_BY_ID_REQUEST = 'SEARCH_CATALOG_BY_ID_REQUEST'
export const SEARCH_CATALOG_BY_ID_SUCCESS = 'SEARCH_CATALOG_BY_ID_SUCCESS'
export const SEARCH_CATALOG_BY_ID_FAILURE = 'SEARCH_CATALOG_BY_ID_FAILURE'

export const UNMOUNT_CATALOG = 'UNMOUNT_CATALOG';
//fraction
export const GET_FRACTION_REQUEST = 'GET_FRACTION_REQUEST';
export const GET_FRACTION_SUCCESS = 'GET_FRACTION_SUCCESS';
export const GET_FRACTION_FAILURE = 'GET_FRACTION_FAILURE';

export const ADD_FRACTION_REQUEST = 'ADD_FRACTION_REQUEST';
export const ADD_FRACTION_SUCCESS = 'ADD_FRACTION_SUCCESS';
export const ADD_FRACTION_FAILURE = 'ADD_FRACTION_FAILURE';

export const UPDATE_FRACTION_REQUEST = 'UPDATE_FRACTION_REQUEST';
export const UPDATE_FRACTION_SUCCESS = 'UPDATE_FRACTION_SUCCESS';
export const UPDATE_FRACTION_FAILURE = 'UPDATE_FRACTION_FAILURE';

export const DELETE_FRACTION_REQUEST = 'DELETE_FRACTION_REQUEST';
export const DELETE_FRACTION_SUCCESS = 'DELETE_FRACTION_SUCCESS';
export const DELETE_FRACTION_FAILURE = 'DELETE_FRACTION_FAILURE';


//---------------- ACCOUNT -----------------------------
export const GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAILURE = 'GET_ACCOUNT_FAILURE';

export const UPDATE_PERMISSION_REQUEST = 'UPDATE_PERMISSION_REQUEST';
export const UPDATE_PERMISSION_SUCCESS = 'UPDATE_PERMISSION_SUCCESS';
export const UPDATE_PERMISSION_FAILURE = 'UPDATE_PERMISSION_FAILURE';

export const GET_SEARCH_ACCOUNT_REQUEST = 'GET_SEARCH_ACCOUNT_REQUEST';
export const GET_SEARCH_ACCOUNT_SUCCESS = 'GET_SEARCH_ACCOUNT_SUCCESS';
export const GET_SEARCH_ACCOUNT_FAILURE = 'GET_SEARCH_ACCOUNT_FAILURE';

export const POST_ACCOUNT_REQUEST = 'POST_ACCOUNT_REQUEST';
export const POST_ACCOUNT_SUCCESS = 'POST_ACCOUNT_SUCCESS';
export const POST_ACCOUNT_FAILURE = 'POST_ACCOUNT_FAILURE';

export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';

export const PUT_ACCOUNT_REQUEST = 'PUT_ACCOUNT_REQUEST';
export const PUT_ACCOUNT_SUCCESS = 'PUT_ACCOUNT_SUCCESS';
export const PUT_ACCOUNT_FAILURE = 'PUT_ACCOUNT_FAILURE';

//------------------------------------------------------

//---------------- PROJECT_MANAGER -----------------------------
export const GET_PROJECT_MANAGER_REQUEST = 'GET_PROJECT_MANAGER_REQUEST';
export const GET_PROJECT_MANAGER_SUCCESS = 'GET_PROJECT_MANAGER_SUCCESS';
export const GET_PROJECT_MANAGER_FAILURE = 'GET_PROJECT_MANAGER_FAILURE';

export const SEARCH_PROJECT_MANAGER_REQUEST = 'SEARCH_PROJECT_MANAGER_REQUEST';
export const SEARCH_PROJECT_MANAGER_SUCCESS = 'SEARCH_PROJECT_MANAGER_SUCCESS';
export const SEARCH_PROJECT_MANAGER_FAILURE = 'SEARCH_PROJECT_MANAGER_FAILURE';

export const DELETE_PROJECT_MANAGER_REQUEST = 'DELETE_PROJECT_MANAGER_REQUEST';
export const DELETE_PROJECT_MANAGER_SUCCESS = 'DELETE_PROJECT_MANAGER_SUCCESS';
export const DELETE_PROJECT_MANAGER_FAILURE = 'DELETE_PROJECT_MANAGER_FAILURE';

export const RESTORE_PROJECT_MANAGER_REQUEST = 'RESTORE_PROJECT_MANAGER_REQUEST';
export const RESTORE_PROJECT_MANAGER_SUCCESS = 'RESTORE_PROJECT_MANAGER_SUCCESS';
export const RESTORE_PROJECT_MANAGER_FAILURE = 'RESTORE_PROJECT_MANAGER_FAILURE';

export const CHOOSE_PROJECT_TO_UPDATE = 'CHOOSE_PROJECT_TO_UPDATE';
//------------------------------------------------------

//---------------- LIST_PENDING ----------------------------------
export const GET_LIST_PENDING_REQUEST = 'GET_LIST_PENDING_REQUEST'
export const GET_LIST_PENDING_SUCCESS = 'GET_LIST_PENDING_SUCCESS'
export const GET_LIST_PENDING_FAILURE = 'GET_LIST_PENDING_FAILURE'

export const POST_PRODUCT_PENDING_REQUEST = 'POST_PRODUCT_PENDING_REQUEST'
export const POST_PRODUCT_PENDING_SUCCESS = 'POST_PRODUCT_PENDING_SUCCESS'
export const POST_PRODUCT_PENDING_FAILURE = 'POST_PRODUCT_PENDING_FAILURE'

export const PUT_STATUS_PENDING_REQUEST = 'PUT_STATUS_PENDING_REQUEST'
export const PUT_STATUS_PENDING_SUCCESS = 'PUT_STATUS_PENDING_SUCCESS'
export const PUT_STATUS_PENDING_FAILURE = 'PUT_STATUS_PENDING_FAILURE'

//----------------------------------------------------------------
//----------------------------------------------------------------
export const FORGET_ACCOUNT_PASSWORD_REQUEST = 'FORGET_ACCOUNT_PASSWORD_REQUEST'
export const FORGET_ACCOUNT_PASSWORD_SUCCESS = 'FORGET_ACCOUNT_PASSWORD_SUCCESS'
export const FORGET_ACCOUNT_PASSWORD_FAILURE = 'FORGET_ACCOUNT_PASSWORD_FAILURE'

//----------------------------------------------------------------
export const RESET_IS_SUCCESS = 'RESET_IS_SUCCESS'
